[grid]
columns = 2
width   = 1920
height  = 1080
fps     = 30

[[source]]
id     = "rdt-apr"
uri    = "file:///home/locad/Downloads/RDT_20260418_092704.mp4"
volume = 0.15
offset_ms = -1000

[[source]]
id     = "put-down"
uri    = "file:///home/locad/Downloads/Put_Down_1.mov"
volume = 0.15

[[source]]
id     = "xiaoy-1080"
uri    = "file:///home/locad/Downloads/XiaoYing_Video_1761375427042_1080HD.mp4"
volume = 0.15
offset_ms = -1000

[[source]]
id     = "like-a-glove"
uri    = "file:///home/locad/Downloads/Like-a-glove.mp4"
volume = 0.15
